# Generated by Django 5.0 on 2024-03-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "train_no",
                    models.TextField(blank=True, db_column="Train No", null=True),
                ),
                (
                    "train_name",
                    models.TextField(blank=True, db_column="train Name", null=True),
                ),
                ("islno", models.BigIntegerField(blank=True, null=True)),
                (
                    "station_code",
                    models.TextField(blank=True, db_column="station Code", null=True),
                ),
                (
                    "station_name",
                    models.TextField(blank=True, db_column="Station Name", null=True),
                ),
                (
                    "arrival_time",
                    models.TextField(blank=True, db_column="Arrival time", null=True),
                ),
                (
                    "departure_time",
                    models.TextField(blank=True, db_column="Departure time", null=True),
                ),
                (
                    "distance",
                    models.BigIntegerField(blank=True, db_column="Distance", null=True),
                ),
                (
                    "source_station_code",
                    models.TextField(
                        blank=True, db_column="Source Station Code", null=True
                    ),
                ),
                (
                    "source_station_name",
                    models.TextField(
                        blank=True, db_column="source Station Name", null=True
                    ),
                ),
                (
                    "destination_station_code",
                    models.TextField(
                        blank=True, db_column="Destination station Code", null=True
                    ),
                ),
                (
                    "destination_station_name",
                    models.TextField(
                        blank=True, db_column="Destination Station Name", null=True
                    ),
                ),
            ],
            options={
                "db_table": "train_list",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
    ]
